[package]
name = "tu_types"
version = "0.1.0"
edition = "2018"

[lib]
name = "tu_types"
path = "lib.rs"

[dependencies]
marine-rs-sdk = "0.14.0"
serde = "1.0.198"
serde_json = "1.0.116"
rmp-serde = "1.1.2"